import { createId } from "./createId.js";

export type Product = {
    id: string,
    title: string,
    description: string,
    price: number,
    createdAt: Date,
    category: string,
    rating: number,
    owner: string,
    ofert: boolean | null,
    offer_data?: { percent: number, new_value: number, expiresIn: number },
    shipping: boolean | null,
    images: Object | null,
    stock: number
}

export const categories: string[] = [
    "Heladeras",
    "Lavarropas",
    "Microondas",
    "Aires Acondicionados",
    "Cocinas",
    "Televisores",
    "Aspiradoras",
    "Pequeños Electrodomésticos",
    "Ventiladores",
    "Cuidado Personal"
];

export let products: Product[] = [
    // HELADERAS (20 productos)
    {
        id: createId(),
        title: "Heladera Gafa HGF-1800 No Frost",
        description: "Heladera con freezer, tecnología No Frost, 410 litros de capacidad, acero inoxidable",
        price: 850000,
        createdAt: new Date("2024-10-01"),
        category: "Heladeras",
        rating: 4.5,
        owner: "ElectroHogar SA",
        ofert: true,
        offer_data: { percent: 15, new_value: 722500, expiresIn: 72 },
        shipping: true,
        images: {
            thumb: "/images/products_folder/0/Heladera Gafa HGF-1800_1.jpg",
            img: ["/images/products_folder/0/Heladera Gafa HGF-1800_2.webp", "/images/products_folder/0/Heladera Gafa HGF-1800_3.webp"],
        },
        stock: 12
    },
    {
        id: createId(),
        title: "Heladera Whirlpool WRM45 390L",
        description: "Heladera con freezer, frío húmedo, 390 litros, eficiencia energética A",
        price: 695000,
        createdAt: new Date("2024-09-16"),
        category: "Heladeras",
        rating: 4.6,
        owner: "Premium Home",
        ofert: false,
        shipping: true,
        images: {
            thumb: "/images/products_folder/1/Heladera Whirlpool WRM45 390L_1.webp",
            img: ["/images/products_folder/1/Heladera Whirlpool WRM45 390L_2.jpg"],
        },
        stock: 3
    },
    {
        id: createId(),
        title: "Heladera Samsung RT38 Twin Cooling",
        description: "Heladera No Frost 380 litros, Twin Cooling Plus, dispensador de agua",
        price: 920000,
        createdAt: new Date("2024-09-28"),
        category: "Heladeras",
        rating: 4.8,
        owner: "TecnoSur",
        ofert: true,
        offer_data: { percent: 12, new_value: 809600, expiresIn: 96 },
        shipping: true,
        images: {
            thumb: "/images/products_folder/2/Heladera Samsung RT38 Twin Cooling_1.webp",
            img: ["/images/products_folder/2/Heladera Samsung RT38 Twin Cooling_2.webp"],
        },
        stock: 8
    },
    {
        id: createId(),
        title: "Heladera LG French Door 510L",
        description: "Heladera francesa 510 litros, Smart Diagnosis, Door-in-Door",
        price: 1250000,
        createdAt: new Date("2024-10-05"),
        category: "Heladeras",
        rating: 4.9,
        owner: "Premium Home",
        ofert: false,
        shipping: true,
        images: {
            thumb: "/images/products_folder/3/Heladera LG French Door 510L_1.jpg",
            img: ["/images/products_folder/3/Heladera LG French Door 510L_2.webp", "/images/products_folder/3/Heladera LG French Door 510L_3.jpg"],
        },
        stock: 3
    },
    {/** */
        id: createId(),
        title: "Heladera Patrick HPK135 270L",
        description: "Heladera con freezer 270 litros, frío húmedo, color blanco",
        price: 485000,
        createdAt: new Date("2024-10-08"),
        category: "Heladeras",
        rating: 4.2,
        owner: "ElectroHogar SA",
        ofert: true,
        offer_data: { percent: 18, new_value: 397700, expiresIn: 48 },
        shipping: true,
        images: {
            thumb: "/images/products_folder/4/Heladera Patrick HPK135 270L_1.jpg",
            img: ["/images/products_folder/4/Heladera Patrick HPK135 270L_2.webp"],
        },
        stock: 9
    },
    {/** */
        id: createId(),
        title: "Heladera Philco PHCT340 340L",
        description: "Heladera con freezer 340 litros, sistema de control de frío",
        price: 595000,
        createdAt: new Date("2024-09-22"),
        category: "Heladeras",
        rating: 4.3,
        owner: "Comercial del Sur",
        ofert: false,
        shipping: true,
        images: {
            thumb: "/images/products_folder/5/Heladera Philco PHCT340 340L_1.webp",
            img: ["/images/products_folder/5/Heladera Philco PHCT340 340L_2.webp"],
        },
        stock: 5
    },
    {/** */
        id: createId(),
        title: "Heladera Drean DHT-400N No Frost",
        description: "Heladera No Frost 400 litros, display digital, acero inoxidable",
        price: 825000,
        createdAt: new Date("2024-10-10"),
        category: "Heladeras",
        rating: 4.6,
        owner: "TecnoSur",
        ofert: true,
        offer_data: { percent: 10, new_value: 742500, expiresIn: 120 },
        shipping: true,
        images: {
            thumb: "/images/products_folder/6/Heladera Drean DHT-400N No Frost_1.png",
            img: ["/images/products_folder/6/Heladera Drean DHT-400N No Frost_2.webp"],
        },
        stock: 12
    },
    {/** */
        id: createId(),
        title: "Heladera Kohinoor KHD43 430L",
        description: "Heladera con freezer 430 litros, bajo consumo energético",
        price: 715000,
        createdAt: new Date("2024-09-19"),
        category: "Heladeras",
        rating: 4.4,
        owner: "ElectroHogar SA",
        ofert: false,
        shipping: true,
        images: {
            thumb: "/images/products_folder/7/Heladera Kohinoor KHD43 430L_1.jpg",
            img: ["/images/products_folder/7/Heladera Kohinoor KHD43 430L_2.webp"],
        },
        stock: 4
    },
    {/** */
        id: createId(),
        title: "Heladera Electrolux DFN3000P",
        description: "Heladera No Frost 300 litros, sistema Frost Free, color plateado",
        price: 675000,
        createdAt: new Date("2024-10-03"),
        category: "Heladeras",
        rating: 4.5,
        owner: "Premium Home",
        ofert: true,
        offer_data: { percent: 15, new_value: 573750, expiresIn: 60 },
        shipping: true,
        images: {
            thumb: "/images/products_folder/8/Heladera Electrolux DFN3000P_1.jpg",
            img: ["/images/products_folder/8/Heladera Electrolux DFN3000P_2.jpg"],
        },
        stock: 6
    },
    {/** */
        id: createId(),
        title: "Heladera Siam HSI-FR44 440L",
        description: "Heladera con freezer 440 litros, frío seco, dispensador interno",
        price: 795000,
        createdAt: new Date("2024-09-25"),
        category: "Heladeras",
        rating: 4.3,
        owner: "Comercial del Sur",
        ofert: false,
        shipping: true,
        images: {
            thumb: "/images/products_folder/9/Heladera Siam HSI-FR44 440L_1.webp",
            img: ["/images/products_folder/9/Heladera Siam HSI-FR44 440L_2.jpg"],
        },
        stock: 9
    },
    {
        id: createId(),
        title: "Heladera Candy CCDS6172",
        description: "Heladera combinada 320 litros, clase A+, sistema No Frost",
        price: 645000,
        createdAt: new Date("2024-10-07"),
        category: "Heladeras",
        rating: 4.4,
        owner: "TecnoSur",
        ofert: true,
        offer_data: { percent: 20, new_value: 516000, expiresIn: 84 },
        shipping: true,
        images: {
            thumb: "/images/products_folder/10/Heladera Candy CCDS6172_1.jpg",
            img: ["/images/products_folder/10/Heladera Candy CCDS6172_2.jpeg"],
        },
        stock: 1
    },
    {
        id: createId(),
        title: "Heladera Hisense RB390 390L",
        description: "Heladera con freezer 390 litros, Multi Air Flow, eficiencia A",
        price: 725000,
        createdAt: new Date("2024-09-30"),
        category: "Heladeras",
        rating: 4.7,
        owner: "Premium Home",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 8
    },
    {
        id: createId(),
        title: "Heladera Mabe RMS510 510L",
        description: "Heladera side by side 510 litros, dispensador externo, acero",
        price: 1150000,
        createdAt: new Date("2024-10-02"),
        category: "Heladeras",
        rating: 4.8,
        owner: "ElectroHogar SA",
        ofert: true,
        offer_data: { percent: 10, new_value: 1035000, expiresIn: 72 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 7
    },
    {
        id: createId(),
        title: "Heladera Daewoo RTE360 360L",
        description: "Heladera con freezer 360 litros, sistema cíclico, color gris",
        price: 615000,
        createdAt: new Date("2024-09-18"),
        category: "Heladeras",
        rating: 4.2,
        owner: "Comercial del Sur",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 4
    },
    {
        id: createId(),
        title: "Heladera Bosch KDN46 460L",
        description: "Heladera No Frost 460 litros, VitaFresh, iluminación LED",
        price: 1050000,
        createdAt: new Date("2024-10-11"),
        category: "Heladeras",
        rating: 4.9,
        owner: "Premium Home",
        ofert: true,
        offer_data: { percent: 12, new_value: 924000, expiresIn: 96 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 9
    },
    {
        id: createId(),
        title: "Heladera BGH BNF410 410L",
        description: "Heladera No Frost 410 litros, bajo ruido, eficiencia A+",
        price: 785000,
        createdAt: new Date("2024-09-24"),
        category: "Heladeras",
        rating: 4.5,
        owner: "TecnoSur",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 4
    },
    {
        id: createId(),
        title: "Heladera Midea MDRT480 480L",
        description: "Heladera multi puerta 480 litros, inverter, bajo consumo",
        price: 995000,
        createdAt: new Date("2024-10-06"),
        category: "Heladeras",
        rating: 4.6,
        owner: "ElectroHogar SA",
        ofert: true,
        offer_data: { percent: 15, new_value: 845750, expiresIn: 48 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 12
    },
    {
        id: createId(),
        title: "Heladera Consul CRD49 490L",
        description: "Heladera duplex 490 litros, freezer superior, color blanco",
        price: 745000,
        createdAt: new Date("2024-09-27"),
        category: "Heladeras",
        rating: 4.4,
        owner: "Comercial del Sur",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 32
    },
    {
        id: createId(),
        title: "Heladera Eslabón de Lujo ED350",
        description: "Heladera con freezer 350 litros, sistema de frío ventilado",
        price: 625000,
        createdAt: new Date("2024-10-09"),
        category: "Heladeras",
        rating: 4.3,
        owner: "TecnoSur",
        ofert: true,
        offer_data: { percent: 18, new_value: 512500, expiresIn: 120 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 9
    },
    {
        id: createId(),
        title: "Heladera Aurora AUR520 520L",
        description: "Heladera french door 520 litros, smart control, acero inoxidable",
        price: 1275000,
        createdAt: new Date("2024-10-12"),
        category: "Heladeras",
        rating: 4.8,
        owner: "Premium Home",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 6
    },

    // LAVARROPAS (20 productos)
    {
        id: createId(),
        title: "Lavarropas Drean Next 8.12 Eco",
        description: "Lavarropas automático frontal 8kg, 1200 RPM, clase A+++, 16 programas",
        price: 620000,
        createdAt: new Date("2024-09-28"),
        category: "Lavarropas",
        rating: 4.7,
        owner: "TecnoSur",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 7
    },
    {
        id: createId(),
        title: "Lavarropas Samsung WW90 Eco Bubble",
        description: "Lavarropas carga frontal 9kg, 1400 RPM, display LED, Quick Wash",
        price: 785000,
        createdAt: new Date("2024-10-02"),
        category: "Lavarropas",
        rating: 4.8,
        owner: "Premium Home",
        ofert: true,
        offer_data: { percent: 18, new_value: 643700, expiresIn: 96 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 5
    },
    {
        id: createId(),
        title: "Lavarropas LG WM10 Direct Drive",
        description: "Lavarropas 10kg, motor inverter, 6 Motion, carga frontal",
        price: 895000,
        createdAt: new Date("2024-09-20"),
        category: "Lavarropas",
        rating: 4.9,
        owner: "ElectroHogar SA",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 12
    },
    {
        id: createId(),
        title: "Lavarropas Whirlpool WLF70A",
        description: "Lavarropas automático 7kg, 800 RPM, 12 programas, carga superior",
        price: 485000,
        createdAt: new Date("2024-10-05"),
        category: "Lavarropas",
        rating: 4.4,
        owner: "Comercial del Sur",
        ofert: true,
        offer_data: { percent: 12, new_value: 426800, expiresIn: 72 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 1
    },
    {
        id: createId(),
        title: "Lavarropas Philco PHLF806",
        description: "Lavarropas carga frontal 6kg, 1000 RPM, display digital",
        price: 425000,
        createdAt: new Date("2024-09-18"),
        category: "Lavarropas",
        rating: 4.3,
        owner: "TecnoSur",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 11
    },
    {
        id: createId(),
        title: "Lavarropas Electrolux ELAF9000",
        description: "Lavarropas automático 9kg, sistema Jet&Clean, carga frontal",
        price: 745000,
        createdAt: new Date("2024-10-08"),
        category: "Lavarropas",
        rating: 4.6,
        owner: "Premium Home",
        ofert: true,
        offer_data: { percent: 15, new_value: 633250, expiresIn: 48 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 22
    },
    {
        id: createId(),
        title: "Lavarropas Candy CS14 Smart Touch",
        description: "Lavarropas 14kg, conectividad WiFi, app control, carga superior",
        price: 825000,
        createdAt: new Date("2024-09-25"),
        category: "Lavarropas",
        rating: 4.5,
        owner: "ElectroHogar SA",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 5
    },
    {
        id: createId(),
        title: "Lavarropas Patrick LCFS65",
        description: "Lavarropas semiautomático 6.5kg, doble batea, sistema de lavado",
        price: 295000,
        createdAt: new Date("2024-10-11"),
        category: "Lavarropas",
        rating: 4.0,
        owner: "Comercial del Sur",
        ofert: true,
        offer_data: { percent: 20, new_value: 236000, expiresIn: 120 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 3
    },
    {
        id: createId(),
        title: "Lavarropas Drean Concept 5.05G",
        description: "Lavarropas automático 5kg, 600 RPM, carga superior, económico",
        price: 365000,
        createdAt: new Date("2024-09-22"),
        category: "Lavarropas",
        rating: 4.2,
        owner: "TecnoSur",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 3
    },
    {
        id: createId(),
        title: "Lavarropas Bosch WAU28 Serie 6",
        description: "Lavarropas 8kg, motor EcoSilence, VarioDrum, carga frontal",
        price: 1050000,
        createdAt: new Date("2024-10-03"),
        category: "Lavarropas",
        rating: 4.9,
        owner: "Premium Home",
        ofert: true,
        offer_data: { percent: 10, new_value: 945000, expiresIn: 84 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 3
    },
    {
        id: createId(),
        title: "Lavarropas Midea MLE70",
        description: "Lavarropas 7kg, 1000 RPM, 15 programas, eficiencia A+",
        price: 495000,
        createdAt: new Date("2024-09-30"),
        category: "Lavarropas",
        rating: 4.4,
        owner: "Comercial del Sur",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 3
    },
    {
        id: createId(),
        title: "Lavarropas Ariston NLM11 946",
        description: "Lavarropas 9kg, Push & Wash, carga frontal, 1400 RPM",
        price: 725000,
        createdAt: new Date("2024-10-07"),
        category: "Lavarropas",
        rating: 4.6,
        owner: "ElectroHogar SA",
        ofert: true,
        offer_data: { percent: 14, new_value: 623500, expiresIn: 60 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 3
    },
    {
        id: createId(),
        title: "Lavarropas Koh-i-Noor KOH850",
        description: "Lavarropas 8.5kg, carga superior, motor silencioso, 10 programas",
        price: 545000,
        createdAt: new Date("2024-09-16"),
        category: "Lavarropas",
        rating: 4.3,
        owner: "TecnoSur",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 3
    },
    {
        id: createId(),
        title: "Lavarropas Aurora AULA85",
        description: "Lavarropas automático 8.5kg, carga superior, timer digital",
        price: 585000,
        createdAt: new Date("2024-10-10"),
        category: "Lavarropas",
        rating: 4.5,
        owner: "Comercial del Sur",
        ofert: true,
        offer_data: { percent: 16, new_value: 491400, expiresIn: 96 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 3
    },
    {
        id: createId(),
        title: "Lavarropas Hisense WFHV8012",
        description: "Lavarropas 8kg, steam function, carga frontal, 1200 RPM",
        price: 675000,
        createdAt: new Date("2024-09-27"),
        category: "Lavarropas",
        rating: 4.7,
        owner: "Premium Home",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 3
    },
    {
        id: createId(),
        title: "Lavarropas Eslabon de Lujo EDL75",
        description: "Lavarropas 7.5kg, carga superior, sistema de ahorro de agua",
        price: 465000,
        createdAt: new Date("2024-10-01"),
        category: "Lavarropas",
        rating: 4.2,
        owner: "ElectroHogar SA",
        ofert: true,
        offer_data: { percent: 10, new_value: 418500, expiresIn: 48 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 3
    },
    {
        id: createId(),
        title: "Lavarropas Longvie L5516",
        description: "Lavarropas semiautomático 5.5kg, sistema de centrifugado rápido",
        price: 275000,
        createdAt: new Date("2024-09-24"),
        category: "Lavarropas",
        rating: 3.9,
        owner: "Comercial del Sur",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 8
    },
    {
        id: createId(),
        title: "Lavarropas Siam LSI1000",
        description: "Lavarropas 10kg, carga superior, motor industrial, 16 programas",
        price: 695000,
        createdAt: new Date("2024-10-06"),
        category: "Lavarropas",
        rating: 4.4,
        owner: "TecnoSur",
        ofert: true,
        offer_data: { percent: 12, new_value: 611600, expiresIn: 72 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 8
    },
    {
        id: createId(),
        title: "Lavarropas Daewoo DWF-G8550",
        description: "Lavarropas 8.5kg, tecnología wobble, carga superior",
        price: 525000,
        createdAt: new Date("2024-09-19"),
        category: "Lavarropas",
        rating: 4.3,
        owner: "Premium Home",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 8
    },
    {
        id: createId(),
        title: "Lavarropas Mademsa MM712",
        description: "Lavarropas 7kg, carga frontal, 1200 RPM, bajo consumo",
        price: 515000,
        createdAt: new Date("2024-10-12"),
        category: "Lavarropas",
        rating: 4.5,
        owner: "ElectroHogar SA",
        ofert: true,
        offer_data: { percent: 18, new_value: 422300, expiresIn: 120 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 8
    },

    // MICROONDAS (20 productos)
    {
        id: createId(),
        title: "Microondas Samsung MS28J5255UB",
        description: "Microondas digital 28 litros, grill, 6 niveles de potencia",
        price: 145000,
        createdAt: new Date("2024-10-05"),
        category: "Microondas",
        rating: 4.3,
        owner: "Comercial del Sur",
        ofert: true,
        offer_data: { percent: 10, new_value: 130500, expiresIn: 48 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 8
    },
    {
        id: createId(),
        title: "Microondas LG MH7235GPS Grill",
        description: "Microondas con grill 32 litros, tecnología I-Wave, 10 niveles",
        price: 195000,
        createdAt: new Date("2024-09-23"),
        category: "Microondas",
        rating: 4.7,
        owner: "Premium Home",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 6
    },
    {
        id: createId(),
        title: "Microondas Whirlpool WM120AX",
        description: "Microondas 20 litros, 800W, 5 niveles de potencia, blanco",
        price: 95000,
        createdAt: new Date("2024-10-08"),
        category: "Microondas",
        rating: 4.2,
        owner: "ElectroHogar SA",
        ofert: true,
        offer_data: { percent: 15, new_value: 80750, expiresIn: 72 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 8
    },
    {
        id: createId(),
        title: "Microondas Electrolux EME20S1",
        description: "Microondas 20 litros, acero inoxidable, timer mecánico",
        price: 105000,
        createdAt: new Date("2024-09-28"),
        category: "Microondas",
        rating: 4.1,
        owner: "Comercial del Sur",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 6
    },
    {
        id: createId(),
        title: "Microondas Philco PHMM23 Digital",
        description: "Microondas 23 litros, panel digital, 900W, función descongelar",
        price: 115000,
        createdAt: new Date("2024-10-02"),
        category: "Microondas",
        rating: 4.4,
        owner: "TecnoSur",
        ofert: true,
        offer_data: { percent: 12, new_value: 101200, expiresIn: 96 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 6
    },
    {
        id: createId(),
        title: "Microondas BGH Quick Chef B228D",
        description: "Microondas 28 litros, grill 1000W, control táctil",
        price: 165000,
        createdAt: new Date("2024-09-20"),
        category: "Microondas",
        rating: 4.6,
        owner: "Premium Home",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 5
    },
    {
        id: createId(),
        title: "Microondas Patrick PMO 2020B",
        description: "Microondas 20 litros, 700W, mecánico, color negro",
        price: 85000,
        createdAt: new Date("2024-10-11"),
        category: "Microondas",
        rating: 4.0,
        owner: "ElectroHogar SA",
        ofert: true,
        offer_data: { percent: 18, new_value: 69700, expiresIn: 60 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 12
    },
    {
        id: createId(),
        title: "Microondas Atma MD1723GN Grill",
        description: "Microondas 23 litros con grill, 900W, display LED",
        price: 125000,
        createdAt: new Date("2024-09-25"),
        category: "Microondas",
        rating: 4.3,
        owner: "Comercial del Sur",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 5
    },
    {
        id: createId(),
        title: "Microondas Candy CMXG22DS",
        description: "Microondas 22 litros, 800W, plato giratorio, acero",
        price: 118000,
        createdAt: new Date("2024-10-06"),
        category: "Microondas",
        rating: 4.2,
        owner: "TecnoSur",
        ofert: true,
        offer_data: { percent: 10, new_value: 106200, expiresIn: 48 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 5
    },
    {
        id: createId(),
        title: "Microondas Midea MMI20P10",
        description: "Microondas 20 litros, 700W, timer 35 minutos, económico",
        price: 92000,
        createdAt: new Date("2024-09-30"),
        category: "Microondas",
        rating: 4.1,
        owner: "ElectroHogar SA",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 8
    },
    {
        id: createId(),
        title: "Microondas Panasonic NN-ST25JW",
        description: "Microondas 25 litros, tecnología inverter, 900W",
        price: 185000,
        createdAt: new Date("2024-10-03"),
        category: "Microondas",
        rating: 4.8,
        owner: "Premium Home",
        ofert: true,
        offer_data: { percent: 15, new_value: 157250, expiresIn: 120 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 8
    },
    {
        id: createId(),
        title: "Microondas Daewoo KOR-1NOA",
        description: "Microondas 31 litros, 1000W, grill 1200W, display digital",
        price: 175000,
        createdAt: new Date("2024-09-18"),
        category: "Microondas",
        rating: 4.5,
        owner: "Comercial del Sur",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 8
    },
    {
        id: createId(),
        title: "Microondas Bosch BEL523MS0",
        description: "Microondas integrable 20 litros, acero inoxidable, 800W",
        price: 245000,
        createdAt: new Date("2024-10-09"),
        category: "Microondas",
        rating: 4.7,
        owner: "Premium Home",
        ofert: true,
        offer_data: { percent: 12, new_value: 215600, expiresIn: 84 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 8
    },
    {
        id: createId(),
        title: "Microondas Siam SMWO20 Digital",
        description: "Microondas 20 litros, 700W, panel digital, color blanco",
        price: 98000,
        createdAt: new Date("2024-09-27"),
        category: "Microondas",
        rating: 4.0,
        owner: "TecnoSur",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 8
    },
    {
        id: createId(),
        title: "Microondas Eslabon de Lujo EDL28G",
        description: "Microondas 28 litros con grill, 1100W, plato giratorio 31.5cm",
        price: 148000,
        createdAt: new Date("2024-10-01"),
        category: "Microondas",
        rating: 4.4,
        owner: "ElectroHogar SA",
        ofert: true,
        offer_data: { percent: 16, new_value: 124320, expiresIn: 72 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 7
    },
    {
        id: createId(),
        title: "Microondas Peabody PE-MO28",
        description: "Microondas 28 litros, 900W, mecánico, interior de acero",
        price: 112000,
        createdAt: new Date("2024-09-22"),
        category: "Microondas",
        rating: 4.2,
        owner: "Comercial del Sur",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 7
    },
    {
        id: createId(),
        title: "Microondas Hisense H25MOBS1HG",
        description: "Microondas 25 litros, grill, steam clean, 900W",
        price: 155000,
        createdAt: new Date("2024-10-07"),
        category: "Microondas",
        rating: 4.6,
        owner: "Premium Home",
        ofert: true,
        offer_data: { percent: 14, new_value: 133300, expiresIn: 96 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 7
    },
    {
        id: createId(),
        title: "Microondas Longvie LV20MW",
        description: "Microondas 20 litros, 700W, timer mecánico, básico",
        price: 88000,
        createdAt: new Date("2024-09-24"),
        category: "Microondas",
        rating: 3.9,
        owner: "ElectroHogar SA",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 8
    },
    {
        id: createId(),
        title: "Microondas Consul CME25 Easy",
        description: "Microondas 25 litros, 900W, 5 potencias, blanco",
        price: 108000,
        createdAt: new Date("2024-10-10"),
        category: "Microondas",
        rating: 4.3,
        owner: "TecnoSur",
        ofert: true,
        offer_data: { percent: 10, new_value: 97200, expiresIn: 48 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 8
    },
    {
        id: createId(),
        title: "Microondas Aurora AMO30D",
        description: "Microondas 30 litros, digital, grill 1000W, acero inoxidable",
        price: 168000,
        createdAt: new Date("2024-10-12"),
        category: "Microondas",
        rating: 4.5,
        owner: "Comercial del Sur",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 7
    },

    // AIRES ACONDICIONADOS (20 productos)
    {
        id: createId(),
        title: "Aire Acondicionado Split BGH Silent Air 3500W",
        description: "Split frío/calor 3500W, inverter, bajo consumo, función sleep",
        price: 750000,
        createdAt: new Date("2024-09-20"),
        category: "Aires Acondicionados",
        rating: 4.6,
        owner: "ClimaTech",
        ofert: false,
        shipping: false,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 7
    },
    {
        id: createId(),
        title: "Aire Acondicionado Samsung WindFree 3000W",
        description: "Split inverter 3000W, frío/calor, tecnología WindFree",
        price: 895000,
        createdAt: new Date("2024-10-02"),
        category: "Aires Acondicionados",
        rating: 4.8,
        owner: "Premium Home",
        ofert: true,
        offer_data: { percent: 15, new_value: 760750, expiresIn: 72 },
        shipping: false,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 7
    },
    {
        id: createId(),
        title: "Aire Acondicionado LG Dual Cool 4500W",
        description: "Split 4500W, inverter, frío/calor, Gold Fin",
        price: 1050000,
        createdAt: new Date("2024-09-18"),
        category: "Aires Acondicionados",
        rating: 4.9,
        owner: "ClimaTech",
        ofert: false,
        shipping: false,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 7
    },
    {
        id: createId(),
        title: "Aire Acondicionado Philco PHS32 3200W",
        description: "Split frío/calor 3200W, on/off, función sleep",
        price: 485000,
        createdAt: new Date("2024-10-05"),
        category: "Aires Acondicionados",
        rating: 4.3,
        owner: "Comercial del Sur",
        ofert: true,
        offer_data: { percent: 20, new_value: 388000, expiresIn: 96 },
        shipping: false,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 7
    },
    {
        id: createId(),
        title: "Aire Acondicionado Surrey 551IQG 5000W",
        description: "Split 5000W, inverter, WiFi, frío/calor",
        price: 1185000,
        createdAt: new Date("2024-09-25"),
        category: "Aires Acondicionados",
        rating: 4.7,
        owner: "Premium Home",
        ofert: false,
        shipping: false,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 7
    },
    {
        id: createId(),
        title: "Aire Acondicionado Electrolux EACS24 2400W",
        description: "Split 2400W, on/off, solo frío, compacto",
        price: 365000,
        createdAt: new Date("2024-10-08"),
        category: "Aires Acondicionados",
        rating: 4.2,
        owner: "ElectroHogar SA",
        ofert: true,
        offer_data: { percent: 12, new_value: 321200, expiresIn: 48 },
        shipping: false,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 3
    },
    {
        id: createId(),
        title: "Aire Acondicionado Midea Inverter 6000W",
        description: "Split 6000W, inverter, frío/calor, ionizador",
        price: 1295000,
        createdAt: new Date("2024-09-22"),
        category: "Aires Acondicionados",
        rating: 4.8,
        owner: "ClimaTech",
        ofert: false,
        shipping: false,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 3
    },
    {
        id: createId(),
        title: "Aire Acondicionado Carrier 53HVQ 2800W",
        description: "Split 2800W, frío/calor, función turbo",
        price: 725000,
        createdAt: new Date("2024-10-11"),
        category: "Aires Acondicionados",
        rating: 4.5,
        owner: "Premium Home",
        ofert: true,
        offer_data: { percent: 18, new_value: 594500, expiresIn: 120 },
        shipping: false,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 3
    },
    {
        id: createId(),
        title: "Aire Acondicionado Hitachi 3500W Inverter",
        description: "Split inverter 3500W, frío/calor, filtro antipolvo",
        price: 845000,
        createdAt: new Date("2024-09-28"),
        category: "Aires Acondicionados",
        rating: 4.6,
        owner: "Comercial del Sur",
        ofert: false,
        shipping: false,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 3
    },
    {
        id: createId(),
        title: "Aire Acondicionado Whirlpool WA35 3500W",
        description: "Split 3500W, on/off, frío/calor, control remoto",
        price: 595000,
        createdAt: new Date("2024-10-03"),
        category: "Aires Acondicionados",
        rating: 4.4,
        owner: "ElectroHogar SA",
        ofert: true,
        offer_data: { percent: 10, new_value: 535500, expiresIn: 60 },
        shipping: false,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 3
    },
    {
        id: createId(),
        title: "Aire Acondicionado Daikin FTXS35 3500W",
        description: "Split inverter 3500W, frío/calor, tecnología Flash Streamer",
        price: 1150000,
        createdAt: new Date("2024-09-20"),
        category: "Aires Acondicionados",
        rating: 4.9,
        owner: "Premium Home",
        ofert: false,
        shipping: false,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 3
    },
    {
        id: createId(),
        title: "Aire Acondicionado TCL 4000W Smart",
        description: "Split 4000W, WiFi, inverter, app control",
        price: 925000,
        createdAt: new Date("2024-10-06"),
        category: "Aires Acondicionados",
        rating: 4.5,
        owner: "ClimaTech",
        ofert: true,
        offer_data: { percent: 15, new_value: 786250, expiresIn: 84 },
        shipping: false,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 3
    },
    {
        id: createId(),
        title: "Aire Acondicionado Hisense 2500W Inverter",
        description: "Split inverter 2500W, frío/calor, bajo ruido",
        price: 585000,
        createdAt: new Date("2024-09-24"),
        category: "Aires Acondicionados",
        rating: 4.3,
        owner: "Comercial del Sur",
        ofert: false,
        shipping: false,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 3
    },
    {
        id: createId(),
        title: "Aire Acondicionado Panasonic CS-RZ35 3500W",
        description: "Split inverter 3500W, nanoe-G, frío/calor",
        price: 1095000,
        createdAt: new Date("2024-10-09"),
        category: "Aires Acondicionados",
        rating: 4.8,
        owner: "Premium Home",
        ofert: true,
        offer_data: { percent: 12, new_value: 963600, expiresIn: 72 },
        shipping: false,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 3
    },
    {
        id: createId(),
        title: "Aire Acondicionado Frio Calor Sanyo 2200W",
        description: "Split 2200W, on/off, función sleep, básico",
        price: 345000,
        createdAt: new Date("2024-09-27"),
        category: "Aires Acondicionados",
        rating: 4.1,
        owner: "ElectroHogar SA",
        ofert: false,
        shipping: false,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 11
    },
    {
        id: createId(),
        title: "Aire Acondicionado Lennox 5500W Inverter",
        description: "Split inverter 5500W, frío/calor, WiFi ready",
        price: 1345000,
        createdAt: new Date("2024-10-01"),
        category: "Aires Acondicionados",
        rating: 4.7,
        owner: "ClimaTech",
        ofert: true,
        offer_data: { percent: 10, new_value: 1210500, expiresIn: 96 },
        shipping: false,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 11
    },
    {
        id: createId(),
        title: "Aire Acondicionado Longvie 3000W",
        description: "Split 3000W, on/off, frío/calor, función deshumidificador",
        price: 475000,
        createdAt: new Date("2024-09-19"),
        category: "Aires Acondicionados",
        rating: 4.2,
        owner: "Comercial del Sur",
        ofert: false,
        shipping: false,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 11
    },
    {
        id: createId(),
        title: "Aire Acondicionado Fujitsu ASYG09 2700W",
        description: "Split inverter 2700W, frío/calor, bajo consumo",
        price: 825000,
        createdAt: new Date("2024-10-07"),
        category: "Aires Acondicionados",
        rating: 4.6,
        owner: "Premium Home",
        ofert: true,
        offer_data: { percent: 14, new_value: 709500, expiresIn: 48 },
        shipping: false,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 11
    },
    {
        id: createId(),
        title: "Aire Acondicionado Atma ATH32 3200W",
        description: "Split 3200W, on/off, frío/calor, led display",
        price: 525000,
        createdAt: new Date("2024-10-10"),
        category: "Aires Acondicionados",
        rating: 4.3,
        owner: "ElectroHogar SA",
        ofert: false,
        shipping: false,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 11
    },
    {
        id: createId(),
        title: "Aire Acondicionado Noblex NBXIN42 4200W",
        description: "Split inverter 4200W, frío/calor, sistema Smart",
        price: 985000,
        createdAt: new Date("2024-10-12"),
        category: "Aires Acondicionados",
        rating: 4.5,
        owner: "ClimaTech",
        ofert: true,
        offer_data: { percent: 16, new_value: 827400, expiresIn: 120 },
        shipping: false,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 11
    },

    // COCINAS (20 productos)
    {
        id: createId(),
        title: "Cocina Escorial Master 56cm",
        description: "Cocina a gas 4 hornallas, horno con visor, encendido electrónico",
        price: 380000,
        createdAt: new Date("2024-10-08"),
        category: "Cocinas",
        rating: 4.2,
        owner: "ElectroHogar SA",
        ofert: null,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 11
    },
    {
        id: createId(),
        title: "Cocina Whirlpool WFX57DB 56cm",
        description: "Cocina multigas 4 hornallas, horno autolimpiante, grill",
        price: 485000,
        createdAt: new Date("2024-09-25"),
        category: "Cocinas",
        rating: 4.5,
        owner: "Premium Home",
        ofert: true,
        offer_data: { percent: 12, new_value: 426800, expiresIn: 72 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 5
    },
    {
        id: createId(),
        title: "Cocina Patrick CPF8151 51cm",
        description: "Cocina a gas 4 hornallas, horno pizzero, blanca",
        price: 295000,
        createdAt: new Date("2024-10-02"),
        category: "Cocinas",
        rating: 4.0,
        owner: "Comercial del Sur",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 5
    },
    {
        id: createId(),
        title: "Cocina Longvie 18501BF 56cm",
        description: "Cocina multigas 4 hornallas, puerta con visor, negra",
        price: 425000,
        createdAt: new Date("2024-09-28"),
        category: "Cocinas",
        rating: 4.3,
        owner: "TecnoSur",
        ofert: true,
        offer_data: { percent: 15, new_value: 361250, expiresIn: 96 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 5
    },
    {
        id: createId(),
        title: "Cocina Electrolux 56DAX 56cm",
        description: "Cocina eléctrica 4 hornallas vitrocerámica, horno eléctrico",
        price: 695000,
        createdAt: new Date("2024-10-05"),
        category: "Cocinas",
        rating: 4.7,
        owner: "Premium Home",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 5
    },
    {
        id: createId(),
        title: "Cocina Philco COPH8631 86cm",
        description: "Cocina industrial 6 hornallas, doble horno, acero",
        price: 875000,
        createdAt: new Date("2024-09-20"),
        category: "Cocinas",
        rating: 4.6,
        owner: "ElectroHogar SA",
        ofert: true,
        offer_data: { percent: 18, new_value: 717500, expiresIn: 48 },
        shipping: false,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 5
    },
    {
        id: createId(),
        title: "Cocina Siam CSI-56 56cm",
        description: "Cocina a gas 4 hornallas, horno con grill, encendido manual",
        price: 325000,
        createdAt: new Date("2024-10-11"),
        category: "Cocinas",
        rating: 4.1,
        owner: "Comercial del Sur",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 5
    },
    {
        id: createId(),
        title: "Cocina Aurora Argenta Plus 56cm",
        description: "Cocina multigas 4 hornallas, horno autolimpiante, inoxidable",
        price: 545000,
        createdAt: new Date("2024-09-18"),
        category: "Cocinas",
        rating: 4.5,
        owner: "TecnoSur",
        ofert: true,
        offer_data: { percent: 10, new_value: 490500, expiresIn: 120 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 14
    },
    {
        id: createId(),
        title: "Cocina Orbis 958AC3 56cm",
        description: "Cocina a gas 4 hornallas, horno pizzero, color blanco",
        price: 365000,
        createdAt: new Date("2024-10-07"),
        category: "Cocinas",
        rating: 4.2,
        owner: "ElectroHogar SA",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 14
    },
    {
        id: createId(),
        title: "Cocina Ariston A5GG1F 50cm",
        description: "Cocina a gas 4 hornallas, horno a gas, compacta",
        price: 395000,
        createdAt: new Date("2024-09-24"),
        category: "Cocinas",
        rating: 4.4,
        owner: "Premium Home",
        ofert: true,
        offer_data: { percent: 14, new_value: 339700, expiresIn: 60 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 14
    },
    {
        id: createId(),
        title: "Cocina Candy CCGM5151 51cm",
        description: "Cocina multigas 4 hornallas, grill eléctrico",
        price: 415000,
        createdAt: new Date("2024-10-03"),
        category: "Cocinas",
        rating: 4.3,
        owner: "Comercial del Sur",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 14
    },
    {
        id: createId(),
        title: "Cocina Bosch HGA120 60cm",
        description: "Cocina profesional 4 hornallas, horno multifunción",
        price: 1250000,
        createdAt: new Date("2024-09-22"),
        category: "Cocinas",
        rating: 4.9,
        owner: "Premium Home",
        ofert: true,
        offer_data: { percent: 10, new_value: 1125000, expiresIn: 84 },
        shipping: false,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 14
    },
    {
        id: createId(),
        title: "Cocina Koh-i-Noor KOHINOOR 505 56cm",
        description: "Cocina a gas 4 hornallas, horno con visor, encendido electrónico",
        price: 445000,
        createdAt: new Date("2024-10-09"),
        category: "Cocinas",
        rating: 4.4,
        owner: "TecnoSur",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 14
    },
    {
        id: createId(),
        title: "Cocina Eslabon de Lujo EDL56 56cm",
        description: "Cocina multigas 4 hornallas, parrilla enlozada",
        price: 385000,
        createdAt: new Date("2024-09-27"),
        category: "Cocinas",
        rating: 4.2,
        owner: "ElectroHogar SA",
        ofert: true,
        offer_data: { percent: 16, new_value: 323400, expiresIn: 72 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 13
    },
    {
        id: createId(),
        title: "Cocina Mademsa MAXI56 56cm",
        description: "Cocina a gas 4 hornallas, horno pizzero, blanca",
        price: 355000,
        createdAt: new Date("2024-10-01"),
        category: "Cocinas",
        rating: 4.1,
        owner: "Comercial del Sur",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 13
    },
    {
        id: createId(),
        title: "Cocina Atma CCH055N 56cm",
        description: "Cocina multigas 4 hornallas, horno con grill, negra",
        price: 405000,
        createdAt: new Date("2024-10-06"),
        category: "Cocinas",
        rating: 4.3,
        owner: "TecnoSur",
        ofert: true,
        offer_data: { percent: 12, new_value: 356400, expiresIn: 96 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 13
    },
    {
        id: createId(),
        title: "Cocina Peabody PE-SV56 56cm",
        description: "Cocina a gas 4 hornallas, encendido superautomático",
        price: 375000,
        createdAt: new Date("2024-09-19"),
        category: "Cocinas",
        rating: 4.2,
        owner: "ElectroHogar SA",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 13
    },
    {
        id: createId(),
        title: "Cocina Sigma SC656 56cm",
        description: "Cocina multigas 4 hornallas, horno autolimpiante",
        price: 465000,
        createdAt: new Date("2024-10-10"),
        category: "Cocinas",
        rating: 4.5,
        owner: "Premium Home",
        ofert: true,
        offer_data: { percent: 18, new_value: 381300, expiresIn: 48 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 13
    },
    {
        id: createId(),
        title: "Cocina Domec CEXUG 56cm",
        description: "Cocina a gas 4 hornallas, horno con visor, grill",
        price: 425000,
        createdAt: new Date("2024-09-26"),
        category: "Cocinas",
        rating: 4.4,
        owner: "Comercial del Sur",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 13
    },
    {
        id: createId(),
        title: "Cocina Volcan 88656V 86cm",
        description: "Cocina industrial 6 hornallas, doble horno, acero inoxidable",
        price: 925000,
        createdAt: new Date("2024-10-12"),
        category: "Cocinas",
        rating: 4.6,
        owner: "TecnoSur",
        ofert: true,
        offer_data: { percent: 15, new_value: 786250, expiresIn: 120 },
        shipping: false,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 7
    },

    // TELEVISORES (20 productos)
    {
        id: createId(),
        title: "Smart TV Samsung 55'' 4K UHD",
        description: "Televisor LED 55 pulgadas, resolución 4K, sistema operativo Tizen",
        price: 895000,
        createdAt: new Date("2024-10-01"),
        category: "Televisores",
        rating: 4.7,
        owner: "Premium Home",
        ofert: true,
        offer_data: { percent: 15, new_value: 760750, expiresIn: 72 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 7
    },
    {
        id: createId(),
        title: "Smart TV LG 43'' Full HD",
        description: "Televisor LED 43 pulgadas, webOS, ThinQ AI, Full HD",
        price: 545000,
        createdAt: new Date("2024-09-28"),
        category: "Televisores",
        rating: 4.5,
        owner: "ElectroHogar SA",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 7
    },
    {
        id: createId(),
        title: "Smart TV Philips 50'' 4K Android",
        description: "Televisor 50 pulgadas, Android TV, Dolby Vision, 4K UHD",
        price: 725000,
        createdAt: new Date("2024-10-05"),
        category: "Televisores",
        rating: 4.6,
        owner: "Comercial del Sur",
        ofert: true,
        offer_data: { percent: 12, new_value: 638000, expiresIn: 96 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 7
    },
    {
        id: createId(),
        title: "Smart TV TCL 32'' HD",
        description: "Televisor LED 32 pulgadas, Android TV, HD Ready",
        price: 295000,
        createdAt: new Date("2024-09-20"),
        category: "Televisores",
        rating: 4.2,
        owner: "TecnoSur",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 7
    },
    {
        id: createId(),
        title: "Smart TV Sony Bravia 65'' 4K OLED",
        description: "Televisor OLED 65 pulgadas, procesador X1, Google TV, 4K HDR",
        price: 2150000,
        createdAt: new Date("2024-10-08"),
        category: "Televisores",
        rating: 4.9,
        owner: "Premium Home",
        ofert: true,
        offer_data: { percent: 10, new_value: 1935000, expiresIn: 120 },
        shipping: false,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 7
    },
    {
        id: createId(),
        title: "Smart TV Noblex 40'' Full HD",
        description: "Televisor LED 40 pulgadas, sistema operativo propio, Full HD",
        price: 425000,
        createdAt: new Date("2024-09-22"),
        category: "Televisores",
        rating: 4.3,
        owner: "ElectroHogar SA",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 7
    },
    {
        id: createId(),
        title: "Smart TV Hitachi 50'' 4K",
        description: "Televisor LED 50 pulgadas, Android TV, 4K UHD, HDR10",
        price: 675000,
        createdAt: new Date("2024-10-11"),
        category: "Televisores",
        rating: 4.5,
        owner: "Comercial del Sur",
        ofert: true,
        offer_data: { percent: 18, new_value: 553500, expiresIn: 48 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 7
    },
    {
        id: createId(),
        title: "Smart TV BGH 32'' HD",
        description: "Televisor LED 32 pulgadas, sistema Linux, HD Ready",
        price: 275000,
        createdAt: new Date("2024-09-25"),
        category: "Televisores",
        rating: 4.1,
        owner: "TecnoSur",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 7
    },
    {
        id: createId(),
        title: "Smart TV Samsung QLED 55'' 4K",
        description: "Televisor QLED 55 pulgadas, Quantum Dot, 4K, Tizen",
        price: 1450000,
        createdAt: new Date("2024-10-03"),
        category: "Televisores",
        rating: 4.8,
        owner: "Premium Home",
        ofert: true,
        offer_data: { percent: 12, new_value: 1276000, expiresIn: 84 },
        shipping: false,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 1
    },
    {
        id: createId(),
        title: "Smart TV Philco 43'' Full HD",
        description: "Televisor LED 43 pulgadas, sistema Android, Full HD",
        price: 485000,
        createdAt: new Date("2024-09-18"),
        category: "Televisores",
        rating: 4.4,
        owner: "ElectroHogar SA",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 1
    },
    {
        id: createId(),
        title: "Smart TV LG NanoCell 65'' 4K",
        description: "Televisor NanoCell 65 pulgadas, AI ThinQ, 4K HDR",
        price: 1695000,
        createdAt: new Date("2024-10-07"),
        category: "Televisores",
        rating: 4.8,
        owner: "Premium Home",
        ofert: true,
        offer_data: { percent: 15, new_value: 1440750, expiresIn: 72 },
        shipping: false,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 1
    },
    {
        id: createId(),
        title: "Smart TV Hisense 50'' 4K",
        description: "Televisor LED 50 pulgadas, VIDAA U, Dolby Vision, 4K",
        price: 625000,
        createdAt: new Date("2024-09-27"),
        category: "Televisores",
        rating: 4.6,
        owner: "Comercial del Sur",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 1
    },
    {
        id: createId(),
        title: "Aspiradora Robot Philips FC8794/01",
        description: "Aspiradora robot inteligente con navegación láser, aplicación móvil, mapeo de habitaciones y control por voz con Alexa y Google Assistant",
        price: 485000,
        createdAt: new Date("2024-10-15"),
        category: "Aspiradoras",
        rating: 4.7,
        owner: "SmartHome Tech",
        ofert: true,
        offer_data: { percent: 18, new_value: 397700, expiresIn: 72 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 8
    },
    {
        id: createId(),
        title: "Aspiradora Sin Cable Dyson V11 Absolute",
        description: "Aspiradora inalámbrica de alta potencia con tecnología de detección de suciedad, pantalla LCD, 6 modos de limpieza y batería de 60 minutos",
        price: 895000,
        createdAt: new Date("2024-10-10"),
        category: "Aspiradoras",
        rating: 4.9,
        owner: "Premium Home",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 5
    },
    {
        id: createId(),
        title: "Aspiradora con Bolsa Electrolux UltraOne",
        description: "Aspiradora tradicional con sistema de filtrado HEPA, potencia 2000W, capacidad 4L, tecnología ciclónica y manguera extensible de 2 metros",
        price: 285000,
        createdAt: new Date("2024-10-18"),
        category: "Aspiradoras",
        rating: 4.3,
        owner: "ElectroHogar SA",
        ofert: true,
        offer_data: { percent: 15, new_value: 242250, expiresIn: 96 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 12
    },
    {
        id: createId(),
        title: "Aspiradora Vertical Samsung Jet 90",
        description: "Aspiradora vertical ligera con tecnología Jet Cyclone, batería removible, cabezal flexible para muebles y modo turbo para alfombras",
        price: 625000,
        createdAt: new Date("2024-10-12"),
        category: "Aspiradoras",
        rating: 4.6,
        owner: "TecnoSur",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 7
    },
    {
        id: createId(),
        title: "Aspiradora de Agua Kärcher WD 6",
        description: "Aspiradora profesional para seco y húmedo, capacidad 20L, motor de 1300W, ideal para limpieza profunda y recuperación de líquidos",
        price: 425000,
        createdAt: new Date("2024-10-20"),
        category: "Aspiradoras",
        rating: 4.5,
        owner: "Comercial del Sur",
        ofert: true,
        offer_data: { percent: 12, new_value: 374000, expiresIn: 48 },
        shipping: false,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 4
    },
    {
        id: createId(),
        title: "Aspiradora Robot Xiaomi Mi Robot Vacuum",
        description: "Robot aspirador con navegación inteligente, control por app, programación horaria, sensor LDS y compatibilidad con ecosistema smart home",
        price: 355000,
        createdAt: new Date("2024-10-14"),
        category: "Aspiradoras",
        rating: 4.4,
        owner: "SmartHome Tech",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 15
    },
    {
        id: createId(),
        title: "Aspiradora Manual Black+Decker Dustbuster",
        description: "Aspiradora de mano recargable, ideal para auto y pequeños espacios, filtro lavable, luz LED y batería de ion-litio de larga duración",
        price: 125000,
        createdAt: new Date("2024-10-16"),
        category: "Aspiradoras",
        rating: 4.2,
        owner: "ElectroHogar SA",
        ofert: true,
        offer_data: { percent: 20, new_value: 100000, expiresIn: 120 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 20
    },
    {
        id: createId(),
        title: "Aspiradora Industrial Nilfisk GM 80",
        description: "Aspiradora industrial para obras, potencia 2200W, filtro HEPA, capacidad 20L, sistema de auto-limpieza y manguera antiestática",
        price: 785000,
        createdAt: new Date("2024-10-11"),
        category: "Aspiradoras",
        rating: 4.8,
        owner: "Comercial del Sur",
        ofert: false,
        shipping: false,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 3
    },
    {
        id: createId(),
        title: "Aspiradora Sin Bolsa Philips PowerPro",
        description: "Aspiradora ciclónica con tecnología Anti-Allergy, potencia 2000W, depósito XL de 2L, ruedas multidireccionales y boquilla para mascotas",
        price: 345000,
        createdAt: new Date("2024-10-19"),
        category: "Aspiradoras",
        rating: 4.3,
        owner: "Premium Home",
        ofert: true,
        offer_data: { percent: 10, new_value: 310500, expiresIn: 84 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 9
    },
    {
        id: createId(),
        title: "Aspiradora Escalera Atma ASH 1250",
        description: "Aspiradora compacta para escaleras y espacios reducidos, potencia 1250W, bolsa de tela reutilizable y diseño ergonómico para fácil transporte",
        price: 185000,
        createdAt: new Date("2024-10-13"),
        category: "Aspiradoras",
        rating: 4.1,
        owner: "ElectroHogar SA",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 11
    },
    {
        id: createId(),
        title: "Licuadora Osterizer Clásica 3 Velocidades",
        description: "Licuadora profesional con vaso de vidrio refractario de 1.5L, cuchillas de acero inoxidable, 3 velocidades y función pulsar para mayor control",
        price: 95000,
        createdAt: new Date("2024-10-17"),
        category: "Pequeños Electrodomésticos",
        rating: 4.5,
        owner: "ElectroHogar SA",
        ofert: true,
        offer_data: { percent: 15, new_value: 80750, expiresIn: 72 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 18
    },
    {
        id: createId(),
        title: "Batidora de Mano Braun Multiquick 7",
        description: "Batidora de mano profesional con 21 velocidades, tecnología ActiveBlade, motor de 1000W, varilla sumergible de acero y accesorios para múltiples preparaciones",
        price: 185000,
        createdAt: new Date("2024-10-14"),
        category: "Pequeños Electrodomésticos",
        rating: 4.7,
        owner: "Premium Home",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 8
    },
    {
        id: createId(),
        title: "Procesador de Alimentos Philips HR7757",
        description: "Procesador de alimentos con capacidad de 2L, 4 funciones principales, cuchillas de acero inoxidable, tazón de policarbonato y sistema de seguridad integrado",
        price: 225000,
        createdAt: new Date("2024-10-21"),
        category: "Pequeños Electrodomésticos",
        rating: 4.6,
        owner: "TecnoSur",
        ofert: true,
        offer_data: { percent: 12, new_value: 198000, expiresIn: 96 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 6
    },
    {
        id: createId(),
        title: "Cafetera Nespresso Essenza Mini",
        description: "Cafetera de cápsulas compacta, sistema de preparación a 19 bares, calentamiento rápido en 25 segundos, depósito de agua de 0.6L y diseño moderno",
        price: 145000,
        createdAt: new Date("2024-10-16"),
        category: "Pequeños Electrodomésticos",
        rating: 4.4,
        owner: "ElectroHogar SA",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 12
    },
    {
        id: createId(),
        title: "Tostadora Philips HD2581/90",
        description: "Tostadora de 2 ranuras con función de descongelado y recalentamiento, control de tostado personalizable, bandeja extraíble para migas y diseño elegante",
        price: 65000,
        createdAt: new Date("2024-10-19"),
        category: "Pequeños Electrodomésticos",
        rating: 4.3,
        owner: "Comercial del Sur",
        ofert: true,
        offer_data: { percent: 18, new_value: 53300, expiresIn: 48 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 15
    },
    {
        id: createId(),
        title: "Hervidor Eléctrico Russell Hobbs 21670",
        description: "Hervidor de agua de 1.7L con base giratoria 360°, filtro de agua desmontable, apagado automático y iluminación LED azul durante el funcionamiento",
        price: 85000,
        createdAt: new Date("2024-10-12"),
        category: "Pequeños Electrodomésticos",
        rating: 4.5,
        owner: "Premium Home",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 10
    },
    {
        id: createId(),
        title: "Máquina de Pan Black+Decker B2300",
        description: "Máquina para hacer pan con 12 programas preestablecidos, función de masa solamente, temporizador de 15 horas y capacidad para pan de 700g",
        price: 195000,
        createdAt: new Date("2024-10-20"),
        category: "Pequeños Electrodomésticos",
        rating: 4.2,
        owner: "ElectroHogar SA",
        ofert: true,
        offer_data: { percent: 20, new_value: 156000, expiresIn: 120 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 5
    },
    {
        id: createId(),
        title: "Freidora de Aire Philips HD9252/90",
        description: "Freidora de aire sin aceite con tecnología Rapid Air, capacidad de 4.1L, temperatura ajustable 80-200°C, 7 programas y diseño compacto",
        price: 285000,
        createdAt: new Date("2024-10-15"),
        category: "Pequeños Electrodomésticos",
        rating: 4.8,
        owner: "TecnoSur",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 7
    },
    {
        id: createId(),
        title: "Olla Arrocera Oster CKSTRC61",
        description: "Olla arrocera digital de 20 tazas, panel de control táctil, función de mantener caliente, tazón de aluminio antiadherente y cuchara medidora incluida",
        price: 125000,
        createdAt: new Date("2024-10-18"),
        category: "Pequeños Electrodomésticos",
        rating: 4.4,
        owner: "Comercial del Sur",
        ofert: true,
        offer_data: { percent: 10, new_value: 112500, expiresIn: 84 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 9
    },
    {
        id: createId(),
        title: "Exprimidor de Naranjas Philips HR2742",
        description: "Exprimidor de cítricos con cono extra grande, sistema de prensado suave, filtro fino para menos pulpa y diseño compacto para fácil almacenamiento",
        price: 75000,
        createdAt: new Date("2024-10-13"),
        category: "Pequeños Electrodomésticos",
        rating: 4.1,
        owner: "ElectroHogar SA",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 14
    },
    {
        id: createId(),
        title: "Ventilador de Torre Honeywell HYF290",
        description: "Ventilador de torre oscilante de 90cm, 3 velocidades, control remoto, temporizador de 8 horas, función de brisa natural y diseño ultra silencioso",
        price: 125000,
        createdAt: new Date("2024-10-16"),
        category: "Ventiladores",
        rating: 4.6,
        owner: "ClimaTech",
        ofert: true,
        offer_data: { percent: 15, new_value: 106250, expiresIn: 72 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 12
    },
    {
        id: createId(),
        title: "Ventilador de Pie Liliana 18 Pulgadas",
        description: "Ventilador de pie tradicional de 18 pulgadas, 3 velocidades, oscilación automática, malla de protección reforzada y base estable antideslizante",
        price: 85000,
        createdAt: new Date("2024-10-14"),
        category: "Ventiladores",
        rating: 4.3,
        owner: "ElectroHogar SA",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 15
    },
    {
        id: createId(),
        title: "Ventilador de Techo Hunter Original",
        description: "Ventilador de techo con luz LED integrada, control remoto, 5 aspas de madera, 3 velocidades reversible y motor silencioso de alta eficiencia",
        price: 185000,
        createdAt: new Date("2024-10-20"),
        category: "Ventiladores",
        rating: 4.7,
        owner: "Premium Home",
        ofert: true,
        offer_data: { percent: 12, new_value: 162800, expiresIn: 96 },
        shipping: false,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 6
    },
    {
        id: createId(),
        title: "Ventilador USB Portátil Xiaomi Smartmi",
        description: "Ventilador USB recargable, batería de 2000mAh, 3 velocidades, luz nocturna LED, base flexible 360° y diseño compacto para escritorio o viajes",
        price: 45000,
        createdAt: new Date("2024-10-17"),
        category: "Ventiladores",
        rating: 4.4,
        owner: "TecnoSur",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 25
    },
    {
        id: createId(),
        title: "Ventilador con Purificador Dyson Pure Cool",
        description: "Ventilador inteligente con purificador HEPA, conexión WiFi, control por app, sensor de calidad de aire, modo noche y oscilación de 350°",
        price: 895000,
        createdAt: new Date("2024-10-19"),
        category: "Ventiladores",
        rating: 4.9,
        owner: "SmartHome Tech",
        ofert: true,
        offer_data: { percent: 10, new_value: 805500, expiresIn: 120 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 3
    },
    {
        id: createId(),
        title: "Ventilador de Mesa Philco PHVT30",
        description: "Ventilador de mesa de 30cm, 3 velocidades, oscilación automática, agarradera integrada y diseño compacto ideal para dormitorios u oficinas",
        price: 55000,
        createdAt: new Date("2024-10-15"),
        category: "Ventiladores",
        rating: 4.2,
        owner: "Comercial del Sur",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 18
    },
    {
        id: createId(),
        title: "Ventilador de Pared Industrial Frico",
        description: "Ventilador de pared industrial para grandes espacios, motor de 18 pulgadas, velocidad variable, protección IP54 y construcción metálica duradera",
        price: 225000,
        createdAt: new Date("2024-10-21"),
        category: "Ventiladores",
        rating: 4.5,
        owner: "ElectroHogar SA",
        ofert: true,
        offer_data: { percent: 18, new_value: 184500, expiresIn: 48 },
        shipping: false,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 4
    },
    {
        id: createId(),
        title: "Ventilador Sin Aspas Orbegozo A30",
        description: "Ventilador sin aspas con tecnología Air Multiplier, control remoto, 10 velocidades, temporizador y diseño seguro ideal para familias con niños",
        price: 195000,
        createdAt: new Date("2024-10-13"),
        category: "Ventiladores",
        rating: 4.6,
        owner: "Premium Home",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 8
    },
    {
        id: createId(),
        title: "Ventilador de Torre con Humidificador",
        description: "Ventilador de torre 2 en 1 con humidificador integrado, tanque de agua de 2L, ionizador, control táctil y panel LED con indicadores de humedad",
        price: 165000,
        createdAt: new Date("2024-10-18"),
        category: "Ventiladores",
        rating: 4.3,
        owner: "ClimaTech",
        ofert: true,
        offer_data: { percent: 15, new_value: 140250, expiresIn: 84 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 7
    },
    {
        id: createId(),
        title: "Ventilador de Pie BGH B31PX 16 Pulgadas",
        description: "Ventilador de pie económico de 16 pulgadas, 3 velocidades, malla de protección, altura ajustable y motor de cobre de bajo consumo energético",
        price: 75000,
        createdAt: new Date("2024-10-12"),
        category: "Ventiladores",
        rating: 4.1,
        owner: "ElectroHogar SA",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 20
    },
    {
        id: createId(),
        title: "Secador de Pelo Dyson Supersonic",
        description: "Secador de pelo profesional con motor digital, tecnología de iones, 4 boquillas magnéticas, 3 velocidades y control de temperatura inteligente",
        price: 685000,
        createdAt: new Date("2024-10-19"),
        category: "Cuidado Personal",
        rating: 4.8,
        owner: "BeautyTech",
        ofert: true,
        offer_data: { percent: 12, new_value: 602800, expiresIn: 96 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 5
    },
    {
        id: createId(),
        title: "Afeitadora Philips Series 9000",
        description: "Afeitadora eléctrica rotativa con tecnología SenseIQ, 8 direcciones de flexibilidad, cabeza de precisión, sistema de limpieza automática y app conectada",
        price: 325000,
        createdAt: new Date("2024-10-15"),
        category: "Cuidado Personal",
        rating: 4.7,
        owner: "Premium Home",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 9
    },
    {
        id: createId(),
        title: "Plancha de Pelo GHD Platinum+",
        description: "Placa alisadora profesional con tecnología ultra-zone, calentamiento en 25 segundos, sensor de movimiento, cable giratorio 360° y control de temperatura unificado",
        price: 285000,
        createdAt: new Date("2024-10-21"),
        category: "Cuidado Personal",
        rating: 4.9,
        owner: "BeautyTech",
        ofert: true,
        offer_data: { percent: 15, new_value: 242250, expiresIn: 72 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 6
    },
    {
        id: createId(),
        title: "Cepillo Dental Eléctrico Oral-B iO10",
        description: "Cepillo dental eléctrico con tecnología magnética, pantalla LED interactiva, 7 modos de cepillado, sensor de presión y app de seguimiento dental",
        price: 195000,
        createdAt: new Date("2024-10-16"),
        category: "Cuidado Personal",
        rating: 4.6,
        owner: "ElectroHogar SA",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 12
    },
    {
        id: createId(),
        title: "Depiladora Braun Silk-épil 9",
        description: "Depiladora con tecnología SenseIQ, 40 pinzas, luz para depilación precisa, cabezal facial, modo masaje y diseño ergonómico antideslizante",
        price: 225000,
        createdAt: new Date("2024-10-18"),
        category: "Cuidado Personal",
        rating: 4.5,
        owner: "BeautyTech",
        ofert: true,
        offer_data: { percent: 18, new_value: 184500, expiresIn: 120 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 7
    },
    {
        id: createId(),
        title: "Máquina de Cortar Pelo Wahl Elite Pro",
        description: "Cortapelo profesional para uso doméstico, kit completo con 8 guías, motor de alta potencia, tecnología duradera y diseño ergonómico profesional",
        price: 125000,
        createdAt: new Date("2024-10-14"),
        category: "Cuidado Personal",
        rating: 4.4,
        owner: "Comercial del Sur",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 15
    },
    {
        id: createId(),
        title: "Rizador de Pelo Dyson Airwrap",
        description: "Sistema de estilizado completo con tecnología Coanda, 6 accesorios incluidos, control de temperatura inteligente y secado sin daño térmico al cabello",
        price: 785000,
        createdAt: new Date("2024-10-20"),
        category: "Cuidado Personal",
        rating: 4.8,
        owner: "Premium Home",
        ofert: true,
        offer_data: { percent: 10, new_value: 706500, expiresIn: 84 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 3
    },
    {
        id: createId(),
        title: "Limpiador Facial Foreo Luna 3",
        description: "Dispositivo de limpieza facial con tecnología T-Sonic, 8 intensidades, silicona médica, carga USB y app para rutinas personalizadas de skincare",
        price: 185000,
        createdAt: new Date("2024-10-17"),
        category: "Cuidado Personal",
        rating: 4.5,
        owner: "BeautyTech",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 10
    },
    {
        id: createId(),
        title: "Recortadora de Vello Facial Philips",
        description: "Recortadora precisa para barba y bigote, 20 longitudes ajustables, sistema al vacío, cabezal de precisión y diseño ergonómico para máximo control",
        price: 95000,
        createdAt: new Date("2024-10-13"),
        category: "Cuidado Personal",
        rating: 4.3,
        owner: "ElectroHogar SA",
        ofert: true,
        offer_data: { percent: 20, new_value: 76000, expiresIn: 48 },
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 18
    },
    {
        id: createId(),
        title: "Espejo de Aumento con Luz Philips",
        description: "Espejo de belleza con aumento 10x, luz LED regulable en 3 tonos, base antideslizante, sensor táctil y diseño ideal para maquillaje de precisión",
        price: 65000,
        createdAt: new Date("2024-10-12"),
        category: "Cuidado Personal",
        rating: 4.2,
        owner: "Comercial del Sur",
        ofert: false,
        shipping: true,
        images: {
            thumb: "",
            img: [""],
        },
        stock: 22
    },

]

//console.log(products.length);